plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace = 'com.example.oblivion'
    compileSdk 34

    defaultConfig {
        applicationId = 'com.example.oblivion'
        minSdk 25
        targetSdk 34
        versionCode 1
        versionName '0.9.10'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                arguments '-DANDROID_STL=c++_shared', '-DCMAKE_NINJA_FORCE_RESPONSE_FILE=ON'
            }
        }
    }

    packagingOptions {
        // Reduce APK size by compressing large assets
        jniLibs {
            useLegacyPackaging = true
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation 'androidx.fragment:fragment-ktx:1.6.2'
    implementation 'com.google.android.material:material:1.10.0'
}
